-- MySQL Script generated by MySQL Workbench
-- Thu Jan 25 23:54:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumno` (
  `idalumno` INT NOT NULL,
  `matricula` VARCHAR(6) NULL,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`idalumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materia` (
  `idmateria` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idmateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividad` (
  `idactividad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `valor` INT NULL,
  `materia_idmateria` INT NOT NULL,
  `corte` INT NULL,
  PRIMARY KEY (`idactividad`),
  INDEX `fk_actividad_materia1_idx` (`materia_idmateria` ASC),
  CONSTRAINT `fk_actividad_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `mydb`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alumnos_inscritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumnos_inscritos` (
  `alumno_idalumno` INT NOT NULL,
  `materia_idmateria` INT NOT NULL,
  PRIMARY KEY (`alumno_idalumno`, `materia_idmateria`),
  INDEX `fk_alumno_has_materia_materia1_idx` (`materia_idmateria` ASC),
  INDEX `fk_alumno_has_materia_alumno1_idx` (`alumno_idalumno` ASC),
  CONSTRAINT `fk_alumno_has_materia_alumno1`
    FOREIGN KEY (`alumno_idalumno`)
    REFERENCES `mydb`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_materia_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `mydb`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calificaciones` (
  `calificacion` INT NULL,
  `recuperacion` INT NULL,
  `alumno_idalumno` INT NOT NULL,
  `materia_idmateria` INT NOT NULL,
  `actividad_idactividad` INT NOT NULL,
  INDEX `fk_calificaciones_alumno1_idx` (`alumno_idalumno` ASC),
  INDEX `fk_calificaciones_materia1_idx` (`materia_idmateria` ASC),
  INDEX `fk_calificaciones_actividad1_idx` (`actividad_idactividad` ASC),
  CONSTRAINT `fk_calificaciones_alumno1`
    FOREIGN KEY (`alumno_idalumno`)
    REFERENCES `mydb`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificaciones_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `mydb`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificaciones_actividad1`
    FOREIGN KEY (`actividad_idactividad`)
    REFERENCES `mydb`.`actividad` (`idactividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maestro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maestro` (
  `idmaestro` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`idmaestro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maestro_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maestro_materia` (
  `maestro_idmaestro` INT NOT NULL,
  `materia_idmateria` INT NOT NULL,
  PRIMARY KEY (`maestro_idmaestro`, `materia_idmateria`),
  INDEX `fk_maestro_has_materia_materia1_idx` (`materia_idmateria` ASC),
  INDEX `fk_maestro_has_materia_maestro1_idx` (`maestro_idmaestro` ASC),
  CONSTRAINT `fk_maestro_has_materia_maestro1`
    FOREIGN KEY (`maestro_idmaestro`)
    REFERENCES `mydb`.`maestro` (`idmaestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maestro_has_materia_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `mydb`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tutorados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tutorados` (
  `maestro_idmaestro` INT NOT NULL,
  `alumno_idalumno` INT NOT NULL,
  PRIMARY KEY (`maestro_idmaestro`, `alumno_idalumno`),
  INDEX `fk_maestro_has_alumno_alumno1_idx` (`alumno_idalumno` ASC),
  INDEX `fk_maestro_has_alumno_maestro1_idx` (`maestro_idmaestro` ASC),
  CONSTRAINT `fk_maestro_has_alumno_maestro1`
    FOREIGN KEY (`maestro_idmaestro`)
    REFERENCES `mydb`.`maestro` (`idmaestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maestro_has_alumno_alumno1`
    FOREIGN KEY (`alumno_idalumno`)
    REFERENCES `mydb`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
